name: hello-world
on: push
env:
  World: 'Ramya'
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      World: 'Sakshi'
    steps:
      - name: my-step
        run: echo "Hello $World!"
        env:
          World: 'Krati'
